[env:angkasa_base]
extends = esp32s3_base
board = esp32-s3-devkitc-1
board_level = extra
board_build.arduino.memory_type = qio_opi     ; octal PSRAM (R8)
board_upload.flash_size = 8MB                 ; 1U is sold as N8R8
board_build.partitions = default_8MB.csv
build_flags =
  ${esp32s3_base.build_flags}
  -D PRIVATE_HW
  -I variants/esp32s3/diy/angkasa_base
